### PR TITLE
Feature admin improvements

### PR DESCRIPTION
**Pull request by sheagcraig**
Herein I tried to use all of the available options that I could to make the admin site more useful.

Primarily this consists of a few things:
1. Adding more fields to the list displays, including `ForeignKey` references.
1. Adding filters to the list displays based on what I guessed to be the most useful.
1. Reorganizing detail/change pages where appropriate (`Machine` gets a major improvement).
1. Adding search fields where possible to avoid the "Page 1 of 4465" situation currently in effect.
1. Adding inline forms for `ForeignKey` relationships where possible. This allows you to edit members of a `BusinessUnit` on the `BusinessUnit`'s change page, for example.

In some cases I also used the `date_hierarchy` class attribute to make further date filtration possible.

Finally, I added some `GA`-only additions to the top-right menu so you can get to the Admin site and the API Docs without having to enter the address manually.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
This looks great - can I be cheeky and ask that you add in filtering machines by os_family?

**Comment by sheagcraig** [comment]
Aye.

**Comment by sheagcraig** [comment]
Done.

**Comment by grahamgilbert** [comment]
:shipit:

**Pull request merged**
