### PR TITLE
Api docs

### PR DESCRIPTION
**Pull request by sheagcraig**
This is not finished, but I thought I would make this easily visible and start the PR.

This PR is to enable the (already) included django-rest-framework docs site for Sal. Graham has already done the vast majority of the API setup work. This just cleans that work up and updates things to use the new docs site and handle authentication and permissions.

Done:
- Update requirements file to include new django-rest-framework and docs dependencies (pygments and markdown).
- Enable docs site entirely under the `api` url (`api/docs`).
- Web browser access to existing api endpoints will serve an interactive documentation page as well.
- Refactor custom authentication and permissions classes to handle the three possible situations: a Global Admin user, an API Key request, or an Anonymous User with no auth attempted.
- Update serializers to django-rest-framework 3.6's API.

TODO:
- Write docstrings (they get pulled into the doc site automagically)
- Confer with @grahamgilbert and anyone else about the included columns for results.
- RTFM and audit the existing serializer / view structure to as elegantly as possible express all of the things we want to be available.

In case it's not immediately obvious, when you go to the api/docs site, if you're already authenticated to Sal, you'll see authentication: session in the bottom lefthand corner. You can also go straight to this and login if you haven't done so already.

Also, you can switch the code examples to python down there.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
This looks good, I will test when I get a chance. 🙇

**Comment by sheagcraig** [comment]
Okay-my TODO list for this PR is done. I'm not fooling around with changing the nested relationships at all (they'll just be by ID number).

Please let me know what I can do to make it better!

Some thoughts (dang, more TODO list items):
- Need to document somewhere on the documentation site that you can use the `?ordering=` querystring.
- Likewise, I think you can use different operators either in the ViewSet definitions or in the querystrings themselves to do more than just exact matches. If so, documentation of this would be useful at the top of docs.

**Comment by sheagcraig** [comment]
I'm going to try to summarize all of the changes here to make it easier to review.

## General
- Enabled the Django Rest Framework (DRF) documentation site (`sal_url.com/api/docs`).
- Fixed the API authentication setup to allow session sign in to the docs site. Basically, this means you log in with your Django user (whomever you use to sign into the Sal main site) to be able to use the docs site to make interactive requests.
- Move all view-class level permissions and auth code to global settings in `system_settings.py`
- Move all API endpoints to DRF `ModelViewSet` or `ReadOnlyModelViewSet` instances. This greatly automates the mostly boilerplate setup of all endpoints, as well as enables extra features we didn't have before (filtering).
    - Despite documentation to the contrary, `ordering` does not seem to work as a querystring.

## Endpoint Changes
- Most endpoints now use the filter querystring `?filter=<something>` to filter results. The documentation page lists all available filters for each endpoint.
    - The column names are exactly as they are in the python code. In some places, this added flexibility means longer names, the prime example being that in the past, several endpoints expected a mandatory serial parameter. This has been moved to being a filter where it makes sense, but due to the relations between models, may need to be expressed as `?filter=machine__serial` (using the django filter dunder notation to follow relationships).
- Removed `plugin_script_submissions` and just nested them in `plugin_script_rows`
- `pending_updates` and `pending_apple_updates` now allow you to list all rows of data, and use the standard filtering querystrings to filter by machine serial. This means you may also filter by machine hostname, as well as perform a text search using the `?search=` querystring.
`/api/search` removed: This endpoint allowed you to perform a text search for machines. Since this can be done with the `/api/machines/?search=<something>` endpoint, `/api/search` has been removed.
- `/api/search/<id>` originally returned the results of a SavedSearch. It has been removed in favor of...
- `/api/saved_searches`  Now it operates like the other endpoints and returns a list of SavedSearch objects. or an individual saved search with the <id> parameter.
    - You can execute a search through the additional endpoint `/api/search/<id>/execute`. This also uses the `?full` query parameter to control whether you want all `Machine` fields. It defaults to only returning `id`, `serial`, `console_user`, and `last_checkin`. (This is how the Search module is currently coded).
- `/api/machines` grows an extensive list of filter fields, and search capabilities. Basically, all text-based fields on `Machine` are searched when using the `/api/machines/?search=tacos` querystring.
- `/api/machines` also by default provides the "abbreviated" results, meaning it excludes the Munki report which is often quite long. Using the `?fields` or `?fields!` querystring, you can customize the fields you want the API to return or exclude. Full documentation is added into the docs site.

There is a slight discrepancy in that the results of the `/search/views.py` `search_machines()` function uses an even more abbreviated Machine record than the `/api/machines` endpoint when called with argument `full=False`. The fields are currently hardcoded into an overridden `Serializer` to handle this currently. If the search results ever change, this hardcoded field specification would have to change as well.

**Comment by sheagcraig** [comment]
Anything I can do, short of inventing the 28 hour day, to help get this going?

**Comment by grahamgilbert** [comment]
I just need to get testing tbh. Are there any breaking changing other than to `api/search`?

**Comment by sheagcraig** [comment]
Not that come to mind. I know in an ideal world we'd write a test suite for all of this...

**Comment by grahamgilbert** [comment]
I’m just wondering if there is a way to do this without breaking changes. That would be the ideal. If we go with semantic versioning to the letter, breaking changes would mean Sal 4.0.0

**Comment by sheagcraig** [comment]
I see what you're saying. Well, if that's the concern, we could rename some things. I'm a bit rusty on this PR honestly, but it sounds like `/api/search/<id>` in the original code is the same as `/api/search/<id>/execute` in the PR. We could just leave `search` as is and call the new endpoint something else, with a deprecation/replacement plan in place to switch it over in 4.0.

**Comment by sheagcraig** [comment]
Actually, it looks like I changed the name to `saved_searches` to help clarify that distinction anyway; so I think to bridge the gap for the version 3 run, we can just put `search` back in with some documentation about how it's changing.

**Comment by grahamgilbert** [comment]
Sounds good to me. I'll test next week with a view to getting 3.2.9 out of the door in the back half of next week.

**Comment by sheagcraig** [comment]
Yeah, sounds good. I'll drop search back in some time Monday and hopefully we can close this thing out soonish.

**Comment by sheagcraig** [comment]
Okay, I would say this is about as far as I can go on this for the time being.

To run the tests, activate the venv and do `manage.py test api`

**Comment by grahamgilbert** [comment]
Alrighty, I will crack on with testing.

**Comment by grahamgilbert** [comment]
This looks fantastic. I'm going to verify over the next couple of days that all of my integrations on the old api still work, then I'll merge this.

**Pull request merged**
