### PR TITLE
Encode the application paths, and remember to decode for template

### LINKED ISSUE #135: Installed Paths for Application Inventory links do not work
When looking at the detail for an application in the Application Inventory, clicking on the number badge buttons next to any listed installed path results in a "400 Bad Request" error from the server.

URLs are of the form:
`https://sal.myorg.com/inventory/list/all/0/1822/path//Applications/HandBrake.app/`

The problem appears to be the double slash after "path". Removing one of those slashes bypasses the "400 Bad Request" error, but then no results are found:

"All machines where HandBrake path is Applications/HandBrake.app" -- "No data available in table"

### PR DESCRIPTION
**Pull request by sheagcraig**
I think this should fix #135 

I say think, because it works fine without this change on my setup, so I can't say with any certainty whether this introduces any new problems.

The strategy here is to manually quote the application's path value so that the slashes become %2F (slashes are not escaped normally).
No matter what, the resulting link gets double-encoded as %252F; whereas before reverse would happily include the slashes, here it encodes the %25 as %252F. This seems to correctly get decoded by the actual view class when it comes time to pull data from the database. My understanding is that this is happening here: (In the Django URL resolver): https://github.com/django/django/blob/master/django/urls/resolvers.py#L449

While the path seems to get decoded automatically for the purposes of database queries (can't figure out where this happens), it does not for template rendering, so I also unquoted the path for the inventory_list view's display in the `InventoryListView.get_context_data` method.

### CODE REVIEW

**Comment by gregneagle** [comment]
URL now is something like:
https://sal.foo.com/inventory/list/all/0/406/path/%252FApplications%252FAdobe%2520Photoshop%2520CC%25202017%252FAdobe%2520Photoshop%2520CC%25202017.app/

But then I get:
`DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

**Comment by sheagcraig** [comment]
@gregneagle are you using NGINX or Apache?

I'm guessing the error you're seeing is that in your environment at least, the datatables query is looking up literally `%252FApplications...`, where it's getting unquoted to `/Applications...` on my environment (which is the project's docker container with LDAP bolted on).

**Comment by gregneagle** [comment]
It would be sub-optimal if Sal only worked with the precise Nginx+gunicorn config that's been Dockerized, no?  I'm using Apache+mod_wsgi. 

It seems to me the easiest solution is to not insist on URLs that don't have query parameters. This _is_ a query,  `?path=/foo/bar/baz` would avoid the issue I'd think.

**Comment by sheagcraig** [comment]
Yes, I don't think it should matter. Just trying to identify where things are getting quoted/unquoted or not.

I went back and forth between using queries vs. paths when I wrote this. This issue gives weight to using queries instead.

REST doesn't specify that you're *supposed* to do one over the other, but it does say that paths should uniquely identify an object. I can see an interpretation for this case being that the `Application`  is uniquely identified, but then a query is used to filter `InventoryItem`s from that relationship.

I've been meaning to go over the inventory code from top to bottom, so I'll start reconfiguring the URLs unless anyone one else thinks we should stick with this scheme.

For the time being, if you want to test using the Apache `AllowEncodedSlashes` directive with the above changes, that may at least allow it to work until I can get this out.

**Comment by grahamgilbert** [comment]
Want that I should close it or are you planning on fixing it up?

**Comment by sheagcraig** [comment]
I'm trying to figure that out. I haven't been able to figure out how to make this work with querystrings. I'm slogging through the datatablesview code looking for how it's supposed to work.

The other option is to go back to the URL scheme that used paths for version/path. But it means people who are using Apache have to add the `AllowEncodedSlashes` directive. Which is looking better and better as my eyes get more bleary.

**Comment by sheagcraig** [comment]
Okay-here's the update on this. I have a fix for #212, so it doesn't really factor into this.

I would ping @gregneagle again to see if his Apache server works with the updates introduced by #141, or if it needs additional quoting/unquoting.

If Apache works as is, great.

If not, this PR can be updated to quote and unquote the paths in the querystrings. But I'm going to hold off on doing so until somebody says they need it.

**Comment by sheagcraig** [comment]
I would close it. Reopen if somebody wants to run it on Apache and not use the AllowEncodedSlashes directive.

**Pull request closed without merging**
