### PR TITLE
Refactor plugins

### PR DESCRIPTION
**Pull request by sheagcraig**
I'm going to go ahead and open this so I can start fixing stuff that the CI complains about and let others comment and chime in as I go through.

The goal of this (big) refactoring is to clean up a lot of the duplication in the plugin code. My primary goal was to make writing new plugins as easy and clean as possible. To accomplish this, I wrote a series of plugin classes that represent regular plugins, reports, and machine detail plugins.

I am refactoring/cleaning/rewriting my way through all of the plugins that ship with Sal, but to allow 3rd party plugins to continue to work after this PR is merged, I wrote an adapter class and a `PluginManager` to use instead of the stock Yapsy one. Wherever plugins are loaded, the Sal PluginManager determines whether they're new or old school, and if old, wraps it in the adapter so all plugin handling code can use the same API.

I have moved the access handling and initial machine queryset filtration _into_ the `BasePlugin` class from which the others subclass. This makes the plugin_load and report_load views drastically simpler (indeed, `report_load` now _calls_ `plugin_load`), and allows for the possibility of plugins that override this behavior and instead work on different models or work entirely differently.

Along the way, I have continued with code-cleanup and refactoring as I come across it; in general, if I see something that could use some cleaning or refactoring into more idiomatic python, I have done so.

## Summary of changes so far
- New `sal.plugin` module contains all plugin classes, the plugin manager, and utilities, the aforementioned `OldPluginWrapper`, etc.
- New style plugins can be passed in the context (and _are_ by default if you use the `super_get_context` method in your overridden `get_context`), and have a `__repr__` that can be used in template `{% url %} calls (e.g. `{% url machine_list plugin data group_type group_id %}` as well as a title, alleviating the need to add a title to the context every time (`{{ plugin.title }}`).
- Marked locations where code exists to handle old-style plugins so it will be easy to remove after the deprecation period ends.
- `server.urls` drops about half of the routes involving plugins; This rewrite allowed me to use a single template for all plugins (although plugins can override the `get_template(request, **kwargs)` method to still select from multiple templates should more advanced behavior be needed.
- All plugin views now pass a page type and ID, even if they are for the front page. This removes quite a lot of duplicate code. I'm not sure it's a particularly helpful change, but to help indicate to myself while refactoring what had been changed and what hadn't been touched, I updated the view parameters and their expected values to match the inventory app's use of `group_type` and `group_id` rather than `page` and `theid`. Likewise, because it adds some efficiency in a few places, instead of page types `bu_dashboard`, `group_dashboard`, it now uses `business_unit` and `machine_group`. `front'` becomes `all` to indicate the scope of the request rather than the originating view.
- Cryptstatus, Gatekeeper, and MachineDetailSecurity now have some little icons to reinforce the status indications.
- The report view template now indicates which report is actively displayed in the nav bar.
- The `InstallReport` report used an N^2 algorithm to find the installed update descriptions. I rewrote it to use a linear one that should run a lot faster.
- Fixed a minor error in the `sal.decorators.handle_access` method to make it work more like intended (i.e. it does the work of raising 404 if someone makes a request that they shouldn't have permission to). The issue was specifically for `group_type == 'all'` situations; in the past it delegated testing that to client code instead of handling it directly.
- The encryption plugin never rendered as three columns of buttons for me. This has been fixed. I also added a margin to the desktop row (if configured to display) that pushes it off the laptops row to look more consistent with other UI elements.
- Totally unrelated "rider" update: I added the first checkin date to the machine detail view.

### Plugin class namespace clashes
Yapsy does some "magic" stuff behind the scenes. When it instantiates plugins, it munges the class up; if you introspect one it has a class name like `<class 'yapsy_loaded_plugin_Encryption_20.Encryption'>`. This makes things challenging in a couple of ways. First, `super` doesn't always behave the way you expect it to. To work around this, `BasePlugin` has a `super_get_context` which handles this so clients don't have to.

Second, Yapsy freaks out if you `from sal.plugin import MachinesPlugin` (putting `MachinesPlugin` into the namespace of the plugin module) and use `MachinesPlugin` as the base class for your plugin, AND if you have more than one plugin set up like this. This gets really confusing, and has to do with the way yapsy looks for and dynamically loads python modules. The end result is usually that the second plugin can't be located, and so instead of instantiating the plugin, yapsy creates a `MachinesPlugin` class. (I haven't been able to replicate this issue with `ReportPlugin`, but I have with `MachineDetailPlugin`.

The solution is simple-just `import sal.plugin` and then set the baseclass of plugins to `sal.plugin.MachinesPlugin`. This then avoids the namespace clash.

I plan on handling this by creating a good example throughout the Sal plugins and documenting it in updates to the "Writing your own plugins" wiki pages, but if you're worried about this being an issue, I can see about overriding the relevant parts of the yapsy `IPluginLocator` or wherever the problem originates.

### `try`/`except` in Queryset filtration
As I went through, I updated all `except Exception` situations to catch more specific exceptions. I've done this in past PRs as well, so nothing new here. However, in a lot of cases, queryset api calls (mostly `filter`) were in a `try/except` block that I don't think would ever fail. I could be wrong here, but I have looked at each as I went through and came to the conclusion that the try/except could be removed entirely. Should there be something I'm grossly overlooking here, I'd be happy to put them all back in, probably with a utility that turns it into a one-liner in client code. As it stood, probably 50% of plugin `widget_content` and `filter_machines` code was `try/except` boilerplate.

## TODO
- [x] Finish removing now-unneccessary routes from `server.urls`
- [x] Reports have titles, but the template doesn't display them anywhere. I may look at this.
- [x] I think there are some issues to look at with non-macOS machines and the builtin plugins. I'll probably save this for when that may be a situation that we would  have to anticipate.
- [x] Finish rewriting plugins I haven't gotten to.
- [x] Rewrite datatables/tableajax views that use plugin code or are clients of them.
- [x] Ditto for csv code.
- [x] Remove `plugin_type` use throughout since even with wrapped old-school plugins, it can be introspected from class rather than as a property.
- [x] Factor out the duplicated `DEPRECATED_PAGES` table (that I introduced earlier in the PR).
- [x] Ensure that plugin scripts still get run despite renaming some plugins.
- [x] Clean up all plugin-related and plugin-using templates (2 space indents).
- [x] Remove os_families redundancy (use `BasePlugin` method rather than DB field.
- [x] Refactor plugins, detail plugins, reports handling code since they're 90% the same.
- [x] Add os family to other settings views (plugin, report).
- [x] I'm not happy with the name `MachinesPlugin`. Come up with a less confusing name.
- [x] The InstallReport doesn't look right when there are no InstalledUpdates to show.
- [x] Audit documentation regarding plugins.
    - [x] Use all executables found in a script dir as per documentation (but don't ship text files and whatnot.
- [x] Write updating existing plugins doc.
- [x] Investigate adding a property to plugin class that will pull the DB record if possible; this could also include an `enabled` property, since if it is not enabled it will get `DoesNotExist`.
- [x] Clarify in docstrings how PluginManager returns None if it can't find a plugin, rather than raising an exception.
- [x] Make sure all type checks (Widget, ReportPlugin, DetailPlugin) can also handle OldPluginWrapper.
- [x] Change IPluginInfo container class (holds actual plugin instance): container just has name, path, author, webiste data; which, aside from `path`, isn't used. Refactor to just return the plugin itself; set path from Yapsy wrapper onto plugin at instantiation time. This is used by the preflight to `get_plugin_scripts` and nowhere else.
    - [x] Update all locations where `PluginManager` either gets all plugins or gets a plugin by name to no-longer need the `plugin.plugin_object` structure to access the "plugin itself". I've already audited all uses of this and its pretty straightforward once the manager class gets updated to transfer/copy the path.
    - [x] `grep -R -l --exclude '*.pyc' --exclude-dir 'venv*' --exclude sal.log PluginManager *` lists all py code locations.
    - [x] `grep -R -l --exclude '*.pyc' --exclude-dir 'venv*' --exclude sal.log plugin.plugin_object *` has a few template places to fix this nesting.
- [x] DB plugin models description fields are redundant with plugin data; Make sure it's been unused due to above container disentanglement, then remove.
- [x] Go back through plugins and refactor plugin scripts.
    - [ ] Create utility for plugin scripts to simplify returning results (open plist and append data).
- [ ] Write tests to cover plugin class, main plugin handling code.
- [x] Final view and utility reorganization.
- [ ] Add updating existing plugins doc to wiki.
- [ ] Update "how to create a plugin" document using new code" / WIP in plugins dir.
- [ ] Cache machine model names for machinemodelsbar per its TODO from long ago.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
👍 on the direction you are taking so far.

**Comment by sheagcraig** [comment]
More TODO stuff:

1. Clean up all plugin-related and plugin-using templates.

**Comment by sheagcraig** [comment]
## More new stuff
- Titles, descriptions, and context titles for reports.
- Plugins filter out machines which are running an OS that plugin doesn't support.
- Plugins are not shown on a view if none of the Machine members of that view match the plugin's OS families...
- Unless there are no machines; then just show them all.
- Fixed InstallReport so it doesn't look broken when there are no machines for it.
- Plugin/Report/MachineDetailPlugin settings pages now show more information about both active and inactive plugins.
- Fixed bug in MachineDetailPlugin ordering views that would reorder Plugins instead (whoops!)
- Hot nasty performance gains.
- Fixed client plugin script download to match wiki; now all files with a shebang get shipped to and executed on clients rather than just the first one.

**Comment by sheagcraig** [comment]
@grahamgilbert et al; the remaining TODO things are mostly to do with removing now unused code and reorganizing (and writing documentation). 

I would say this is ready to test.

I need to throw all of my non-Sal-repo plugins into it too; the goal is that it will support non-updated plugins until some major-version change in the future when we'll drop out all of the plugin code commented as DEPRECATED.

**Comment by grahamgilbert** [comment]
Still ready to start testing @sheagcraig since you're still pumping out the commits?

**Comment by sheagcraig** [comment]
@grahamgilbert have at it. The remaining TODO items are post-merge or will be turned into separate PRs.

That being said, this PR is currently at 99 commits... I feel like I could do just one more to make it a nice even 💯

**Comment by sheagcraig** [comment]
Hah. Found something.

I'm not sure why `non_ui_views` has a `preflight_v2` and a `preflight_v2_get_script` which do _nearly_ the same thing. One thing is, they can be refactored to eliminate the duplicated parts.

Secondly, `utils.get_plugin_scripts` needs to probably not fetch scripts if the client machine is not using an OS supported by that plugin.

So I'll work on a 100th commit.

**Comment by sheagcraig** [comment]
Guwa ha ha! 💥 💯 💥

**Comment by clburlison** [comment]
Okay so I honestly haven't reviewed the commits. Can't say I knew the code base well enough before these changes to offer too much feedback. I'm assuming based off the commit messages this only affects plugins. With that said I have custom plugins and they should work without me making changes. They do so 👍 

Side note: it is was easier to read the built-in plugins after this refactor. 👍 I'll work on trying to update my custom plugins when I get some more free time.

Now my only issue (and maybe I'm wrong), currently the following output is dumping to stdout when `DEBUG = False`.

```bash
WARNING:root:Plugin 'FooStatus' needs to be updated to subclass a Sal Plugin!
WARNING:root:Plugin 'Battery' needs to be updated to subclass a Sal Plugin!
WARNING:root:Plugin 'BarPlugin' needs to be updated to subclass a Sal Plugin!
```

Although that message is helpful I've managed to take down a sal server because I left `DEBUG = True` and didn't cleanup these logs. These warnings should really only be seen when DEBUG is enabled.

**Comment by sheagcraig** [comment]
That's good feedback sir; let me look through the code to see if I can find a canonical logging statement to copy which honors the debug preferences.

Of course, that being said, production servers are definitely not going to be running in debug mode, so this was an attempt at alerting people to update their stuff.

**Comment by grahamgilbert** [comment]
I'm pretty happy with this. Gonna give it the merges

**Pull request merged**
