### PR TITLE
Ohai Support

### PR DESCRIPTION
**Pull request by erikng**
Adds Ohai Support
Moves MSC Conditions to tab2-5 so Ohai is in same position as Facter (on machine_detail).

This also fixes a minor bug I ended up finding with the current [code](https://github.com/erikng/sal/blob/c0685945a0951efa1891325a8f2ca576d2c3b25b/server/views.py#L1408-L1409)

### CODE REVIEW

**Comment by niccol** [comment]
I will be out of the office through Monday, October 3rd. For technical
support, please submit a ticket using Web Help Desk. Thanks!

CONFIDENTIALITY NOTICE & ABUSE REPORTING:
This message and any attachments are confidential and may be protected by state and/or federal law.  
If you are not the named recipient of this message, you are hereby notified that any disclosure, copying,
distribution or use of this message or any attachment is prohibited.  If you have received this message in
error, please notify the sender immediately by replying to the sender and delete this copy from your system.  
Thank you for your cooperation.  If you would like to report an inappropriate message that was sent to you
please forward the message to email@glenbard.org

Be Green Keep It On Screen - Do Not Print This Message

**Comment by erikng** [comment]
@niccol if possible, next time, please fix your OOO alerts so you don't spam GitHub repo's that you watch.

**Comment by grahamgilbert** [comment]
I'm going to bump this back to a later release. Once we've solved all the potential `nil` values on the client scripts, and the way we're processing data (you'll thank me on that one...), we can get this merged.

**Comment by erikng** [comment]
No problem. It will be a few weeks before I can even work on the refactor, so once Sal 3 is out, I'll look at the code and figure out the new way to store the data.

On Nov 5, 2016, at 2:07 AM, Graham Gilbert <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm going to bump this back to a later release. Once we've solved all the potential nil values on the client scripts, and the way we're processing data (you'll thank me on that one...), we can get this merged.

-

**Comment by keeleysam** [comment]
This should also be an opt-in feature.  I do not want Sal blindly executing ohai just because it is installed.

**Comment by erikng** [comment]
Then that should go both ways, unless you guys want to definitively state that sal is designed around facter.

On Nov 5, 2016, at 8:15 AM, Samuel Keeley <notifications@github.com<mailto:notifications@github.com>> wrote:


This should also be an opt-in feature. I do not want Sal blindly executing ohai just because it is installed.

-

**Comment by grahamgilbert** [comment]
Neither. If either are installed, the assumption is you want them run. They will both need to be explicitly disabled in the client prefs. I'll add this for Facter, and we'll need it added for ohai when the time comes.

**Comment by grahamgilbert** [comment]
Gonna close this as it's based on the old code. Feel free to revisit if you want to update it.

**Comment by erikng** [comment]
No problem. I'll probably have to at some point.

On Jan 12, 2017, at 3:28 PM, Graham Gilbert <notifications@github.com<mailto:notifications@github.com>> wrote:


Gonna close this as it's based on the old code. Feel free to revisit if you want to update it.

-

**Pull request closed without merging**
