### PR TITLE
Datatables inventory

### PR DESCRIPTION
**Pull request by sheagcraig**
This is not ready, but I wanted to get the PR set up so we can record discussion here.

Outstanding issues that I see:
- Still need to handle Business Unit and Machine Group views.
- Profile making sets with python vs. postgres.
- Permission handling
- Migration currently just drops inventory data.
    - I have forward and reverse functions to do this, but they don't work due to some constraint issues.
- I haven't done any tweaking of datatables via the template's included script tag.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
My first question would be, what does using ``django-datatable-view`` have over how I did it by hand? If it's better I have no issue going whole hog into it, but I want to keep things consistent.

Another quick thing - you can require auth for a view by using the ``@login_required`` decorator rather than doing it in ``urls.py``

**Comment by sheagcraig** [comment]
I'm not totally sold on datatable-view either. What it gets us, as far as I can tell, is "free" filtering, and filtering without needing a page reload. I did it three different ways to test with: one by just modifying your existing code, one with django_tables2, and one with datatable-view. I think that the support for datatable-view is already present in Sal, and it would pretty easy to swap out all list views to use it. This would (probably) provide a better user experience due to the filtering and no page reloading.

I think it makes the code a little cleaner too. The tradeoff is of course that you need to _know_ something about datatable-view to understand what it's replacing, but I think it could reduce all of the list views in Sal by quite a few LOC.

I think another thing is that there is pagination code that you've written in a lot of these functions. I'm using the builtin Django paginator. This isn't really a property of datatable-view, however, so I wouldn't put it in the "for" column. However, I would argue that making use of Django's pagination code rather than repeating the same pagination code in each view that needs pagination is smart.

As mentioned on slack, you can't decorate a class based view in Django 1.8. You _can_ override the dispatch method and decorate it (which I did for dbedc5e).

**Comment by sheagcraig** [comment]
Hey @grahamgilbert. So I came back to see what I was looking at in terms of using your datatables code to make a Sal-specific implementation of a DataTablesView.

It turns out that I never used django-datatables-view. I used django-tables2, which doesn't do anything with DataTables. It seems shrouded in the mists of history at this point, but I remember trying both and got things working quicker with the django-tables2 plugin.

The goal with the datatables use was to improve the performance of the inventory. However, that's addressed by the model changes and sharpening up the queries to match. I haven't loaded a truly enormous set of data into it, but in my testing it seems like a big improvement performance-wise.

And the feature-set is vastly improved.

So here's me making a case for getting this merged sooner rather than later:
A.) There's no datatables conflict at the moment.
B.) The greatly expanded inventory features compensate for the different approach (CBV vs. functions).

Once I get my next major work landmark done and past, and the conferences are done for the summer, I'd be happy to start going through and cleaning up the rest of Sal in the same way: linting, refactoring, performance tuning; one module at a time. I just can't devote that much time at the moment.

Also, I think there's a fair few opportunities to refactor to either the django-tables2 CBVs (which cuts out all of the page indexing code and is very concise and easy once you get the hang of it), or start replacing the inventory with some form of datatables View subclass (either home-brewed or as a plugin), followed by other good candidates for tables replacements.

**Comment by grahamgilbert** [comment]
Alrighty, agreed working is better than perfect. I'll review it tomorrow with the view of doing a release soon. 

Sent from my iPhone




On Tue, May 17, 2016 at 6:32 AM -0700, "Shea Craig" <notifications@github.com> wrote:












Hey @grahamgilbert. So I came back to see what I was looking at in terms of using your datatables code to make a Sal-specific implementation of a DataTablesView.



It turns out that I never used django-datatables-view. I used django-tables2, which doesn't do anything with DataTables. It seems shrouded in the mists of history at this point, but I remember trying both and got things working quicker with the django-tables2 plugin.



The goal with the datatables use was to improve the performance of the inventory. However, that's addressed by the model changes and sharpening up the queries to match. I haven't loaded a truly enormous set of data into it, but in my testing it seems like a big improvement performance-wise.



And the feature-set is vastly improved.



So here's me making a case for getting this merged sooner rather than later:

A.) There's no datatables conflict at the moment.

B.) The greatly expanded inventory features compensate for the different approach (CBV vs. functions).



Once I get my next major work landmark done and past, and the conferences are done for the summer, I'd be happy to start going through and cleaning up the rest of Sal in the same way: linting, refactoring, performance tuning; one module at a time. I just can't devote that much time at the moment.



Also, I think there's a fair few opportunities to refactor to either the django-tables2 CBVs (which cuts out all of the page indexing code and is very concise and easy once you get the hang of it), or start replacing the inventory with some form of datatables View subclass (either home-brewed or as a plugin), followed by other good candidates for tables replacements.

**Comment by grahamgilbert** [comment]
When I try to migrate the db, I get

```
ImportError: No module named datatableview
```

**Comment by grahamgilbert** [comment]
So I installed the missing dependency (`pip install django-datatable-view==0.8.3`). Migration starts.

```
(sal) ~/s/M/sal ❯ python manage.py migrate                                                  sheagcraig-datatables-inventory ✭ ◼
Operations to perform:
  Synchronize unmigrated apps: sal, staticfiles, admindocs, messages, api, django_tables2, datatableview, bootstrap3
  Apply all migrations: watson, sessions, admin, contenttypes, auth, server, sites, catalog, inventory, licenses
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying inventory.0003_auto_20160216_1756...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/graham_gilbert/Dropbox/src/Mine/sal/inventory/migrations/0003_auto_20160216_1756.py", line 10, in migrate_inventoryitems_to_applications
    app, _ = Application.objects.get_or_create(
NameError: global name 'Application' is not defined
```

So I add in `Application = apps.get_model("inventory", "Application")` to the below file and try to migrate again. There's more going wrong on this than I have time to debug today, any thoughts?

```
(sal) ~/s/M/sal ❯ subl /Users/graham_gilbert/Dropbox/src/Mine/sal/inventory/migrations/0003_auto_20160216_1756.py
(sal) ~/s/M/sal ❯ subl .                                                                    sheagcraig-datatables-inventory ✭ ◼
(sal) ~/s/M/sal ❯ python manage.py migrate                                                  sheagcraig-datatables-inventory ✭ ◼
Operations to perform:
  Synchronize unmigrated apps: sal, staticfiles, admindocs, messages, api, django_tables2, datatableview, bootstrap3
  Apply all migrations: watson, sessions, admin, contenttypes, auth, server, sites, catalog, inventory, licenses
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying inventory.0003_auto_20160216_1756...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/graham_gilbert/virtualenvs/sal/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/graham_gilbert/Dropbox/src/Mine/sal/inventory/migrations/0003_auto_20160216_1756.py", line 12, in migrate_inventoryitems_to_applications
    bundleid=item.get("bundleid", ""),
AttributeError: 'InventoryItem' object has no attribute 'get'
```

**Comment by grahamgilbert** [comment]
@sheagcraig I would really like to get this merged in soon. Would you be able to rebase this off the current master? I've still not been able to get this to migrate correctly...

**Comment by grahamgilbert** [comment]
I'm still getting `AttributeError: 'InventoryItem' object has no attribute 'bundleid'`

**Comment by sheagcraig** [comment]
I'm still trying to get this thing to rebase.

**Comment by sheagcraig** [comment]
TODO:
- Fix machine view (says filter by machine: none)
- Redesign ApplicationDetailView to match other app views
- CSV Export use Application name rather than bundleid

**Comment by grahamgilbert** [comment]
Closing this since we've got all this elsewhere

**Pull request closed without merging**
