### PR TITLE
MS ActiveDirectory/LDAP authentication backend with group to profile and business unit mapping

### PR DESCRIPTION
**Pull request by haribert**
This pull request enables authentication against ActiveDirectory/LDAP with mapping of AD/LDAP groups to user profile and business units:
* It binds to the configured AD/LDAP server with username and password from the SAL/django user login.
* Creates a SAL/django user with field information from AD/LDAP (no password is stored in django!)
* Sets SAL user profile (GA, RW, RO) based on their AD/LDAP group.
* Assigns users to SAL business units based on their AD/LDAP group.
* Updates the user profile and business unit assignment at every login of the user.

To enable AD/LDAP authentication, following settings are necessary:
```
AUTHENTICATION_BACKENDS = [
    'server.ADAuthentication.ADAuthentication',
    'django.contrib.auth.backends.ModelBackend',
]
AUTH_LDAP_SERVER_URI = 'ldaps://hostname.company.com:636'
AUTH_LDAP_USER_DOMAIN = ‘company.com’
AUTH_LDAP_USER_SEARCH = 'DC=department,DC=ads,DC=company,DC=com'
AUTH_LDAP_USER_ATTR_MAP = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}
AUTH_LDAP_USER_PREFIX = 'ldap_' # Prefix of django username compared to ldap username

# LDAP SAL Mapping
AUTH_LDAP_USER_PROFILE = {
                            'RO': ('CN=users-all,DC=department,DC=ad,DC=company,DC=com',),
                            'RW': ('CN=service-desk,DC=department,DC=ad,DC=company,DC=com',
                                   'CN=group-leader,OU=group,DC=department,DC=ad,DC=company,DC=com'),
                            'GA': 'CN=admin,DC=department,DC=ad,DC=company,DC=com',
                        }

AUTH_LDAP_USER_PROFILE = {
                            'RO': ('CN=users-all,DC=department,DC=ad,DC=company,DC=com',),
                            'RW': ('CN=service-desk,DC=department,DC=ad,DC=company,DC=com',
                                   'CN=group-leader,OU=group,DC=department,DC=ad,DC=company,DC=com'),
                            'GA': 'CN=admin,DC=department,DC=ad,DC=company,DC=com',
                        }
```

Detailed instructions can be found in the header of `ADAuthentication.py` as markdown. These part can be transferred to the [wiki](https://github.com/salopensource/sal/wiki/LDAP-integration) at a later stage.

We thought this change might be interesting for several SAL installations in business environment. Therefore we wanted to share our implementation and hope you can make use of it.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
This looks great, but there is already an LDAP version which desperately needs some love. Might we be able to move this over there? https://github.com/macadmins/sal-ldap

**Comment by haribert** [comment]
`sal-ldap` is just a wrapper of the [auth ldap backend of django](https://django-auth-ldap.readthedocs.io/en/latest/). It does not integrate to sal itself, it just renames the setting variables to make it compliant to `django-auth-ldap`. But users do not get access to business units or assigned user profiles. Furthermore, an AD/LDAP service account is needed, which is an overkill from my point of view.

This pull request integrates in sal, adds all user profiles and access to the business units. Therefore it would make sense to make it part of sal instead of an own repository. Which makes it much easier to configure and integrate it in docker containers.
If you have an own repository for this, you need to copy/change the `ADAuthenticator.py` and `settings.py` at two different locations (directory `sal` and `server`) and make sure that the version of `ADAuthenticator.py` is compatible with the version of sal. I would prefer to have it included in the main repository (and you can advertise that sal has an integrated AD/LDAP connector).
Nevertheless, the untended [sal-ldap](https://github.com/macadmins/sal-ldap) repository would be obsolete with this pull request.

**Comment by grahamgilbert** [comment]
My concern with having this in the main repo implies support from the maintainers. I do not bind anything directly to AD / LDAP anymore so would not be able to verify anything is broken. I would rather these changes replace sal-ldap as a separate repo (for which I can delegate access to those interested in maintaining this).

**Comment by grahamgilbert** [comment]
Any thoughts on this?

**Comment by haribert** [comment]
Sorry, I had to discuss this first with my co-author. This is now done.

For us the best solution would be to integrate it in this repository. But we can understand your concern.
The question is, can you give us full access to the [sal-ldap](https://github.com/macadmins/sal-ldap) repository or should we create an own repository? The sal-ldap repository would be our preferred option, this repository should anyway get obsolete with our solution.

**Comment by grahamgilbert** [comment]
Agreed. I've just moved the repo to this org, let me know who should have commit access.

**Comment by gregneagle** [comment]
The LDAP configuration/mappings here are not general-purpose, but rather AD-specific. I don't have any objection per se to that, but I think the documentation/description should be clear that the mappings are specific to AD, and if your org uses a different LDAP schema (for example RFC2307/RFC2307bis) then much customization must be done.

**Comment by haribert** [comment]
Sorry for my irregular updates, I only work part time on this project.

@gregneagle It is true, it is very AD-specific. Therefore it is called ADAuthentication and I tried to make this clear in the documentation (I always mentioned AD/LDAP and never ldap alone).
There is a remark as "_Possible improvements_" to make it work with other LDAP implementations as well.

So it would make sense to have an own repository called **sal-ActiveDirectory** as long as this connector is AD specific?

**Comment by haribert** [comment]
@grahamgilbert Can you please add @aschwanb to to sal-ldap Repository as well? Thank you.

**Comment by haribert** [comment]
We decided to use an own repository for this and leave [sal-ldap](https://github.com/salopensource/sal-ldap) as it is.
Our work is currently pushed to [haribert/sal-ActiveDirectory](https://github.com/haribert/sal-ActiveDirectory). I do not have the rights to create an own repository in the salopensource context. Can you please create the repository `sal-ActiveDirectory` and give @haribert and @aschwanb full access to to it? You can remove my account from sal-ldap instead.
Is it possible that you link this repository to docker hub as well?

**Comment by grahamgilbert** [comment]
Sure. Minor nit - can the repo name be lower cased please.

**Comment by haribert** [comment]
Lower case is ok for me.

**Comment by haribert** [comment]
Any news concerning the repository?
I will close this PR as soon as the code is checked into the repository. The best would be, if the docker container would exist as well. Thanks for your help.

**Comment by clburlison** [comment]
@haribert for what it’s worth Graham is at a conference right now so this might not happen until he gets back.

**Comment by grahamgilbert** [comment]
Done

**Comment by haribert** [comment]
Just pushed my stuff to the repository. It took a little longer, because there was already a request for a feature.
Updated wiki page as well.

**Pull request closed without merging**
