### PR TITLE
prune results from BU that user should have no access to

### PR DESCRIPTION
**Pull request by epackorigan**
exporting to CSV would cause records to come back that the end user may not have access to.

### CODE REVIEW

**Comment by sheagcraig** [comment]
I think you could also do something akin to this:
```
machines = Machine.objects.all()
if request.user.userprofile.level != 'GA':
    machines = machines.filter(machine_group__business_unit__id__in=u.businessunit_set.values('id'))
```

I'm not sure which would be more performant!

**Comment by sheagcraig** [comment]
I just timed the worst case scenario (non-GA user, lots of BusinessUnits, decent amount of machines, and converting the queryset to a list after), and they weren't that far off; but, I have some reservations about my timeit method, because each individual iteration took _way_ longer than I expected.

**Comment by grahamgilbert** [comment]
Any further thoughts on this @epackorigan ?

**Comment by epackorigan** [comment]
I haven't had a chance to work on sal this last couple weeks, and probably won't be able to touch them for another 1 or 2... (unless i can hide in the office for some time over the weekend)

**Comment by sheagcraig** [comment]
It's been about 18 months... Any updates @epackorigan or shall we close this?

**Comment by epackorigan** [comment]
Sorry. I have no time to dedicate to this at the moment. 

Did things change with sal4 on that front?

**Comment by sheagcraig** [comment]
Fixed with #341

**Pull request closed without merging**
