### PR TITLE
Inventory Model - add Win32_Package Fields - Windows packages and upd…

### PR DESCRIPTION
**Pull request by lemonaidgyoung**
Add Inventory support for Windows software packages and updates

I would like to add Win32_Package and Win32_QuickFixEngieering class fields
IE: Add Microsoft Windows installed packages and updates to the Inventory model.

This commit adds the data model and view (plus search fields and filters)

### CODE REVIEW

**Comment by grahamgilbert** [comment]
Is there a reason the variables are camel case rather than snake case used throughout the rest of the application? Other than that, lgtm. I assume exposing this in the GUI is next up?

**Comment by lemonaidgyoung** [comment]
> re: Is there a reason the variables are camel case rather than snake case used throughout the rest of the application? 
An oversight, I'll fix the commit to reflect the convention
> .. I assume exposing this in the GUI is next up?
Correct, wanted to get the data model in 1 commit and UI in another

**Comment by gjyoung1974** [comment]
do not merge. Preparing a new PR

**Comment by lemonaidgyoung** [comment]
do mot merge

**Pull request closed without merging**
