### PR TITLE
Add SalSetting for, and link button to, Crypt in, FileVault Escrow plugin.

### PR DESCRIPTION
**Pull request by sheagcraig**
This adds a button that will take you to Crypt if you have `crypt_url` as a SalSetting.

Pending merge, I'll update the settings wiki page to indicate how this works.

I guess technically this URL doesn't have to go to Crypt... Not sure what else it would go to though.

I also cleaned up the template a bit.

Unfortunately, Crypt's URLs are by machine ID rather than by serial number, so I couldn't construct a link directly to that machine's info page.

If you want, let me know and we can just sit on this one and can add in a route for Crypt to accept serial numbers instead of just IDs, thus making this even more useful (our employee service desk asks for this all the time).

### CODE REVIEW

**Comment by erikng** [comment]
This would be really awesome if the crypt part was written as well. Great idea!

**Comment by grahamgilbert** [comment]
This should be pretty easy to add to crypt, let’s wait on merging this until the additional route is in crypt.

**Comment by grahamgilbert** [comment]
And maybe (if we’re being fancy) some UI to add this in the settings UI?

**Comment by sheagcraig** [comment]
Settings UI would be good.

I'm sitting on some code that I need to PR that will wrap the SalSetting model so that we can set up a dictionary of all of the known settings and what we want their default values to be. Then, whenever you retrieve a setting, it will check and see if they've been created yet and set them up if they haven't. That way you would (eventually) get all of the default settings in the DB without having to manually add them.

(hint-the SalSetting admin page would also use this so you would never _not_ see them.)

**Comment by sheagcraig** [comment]
https://github.com/grahamgilbert/Crypt-Server/pull/51

**Comment by erikng** [comment]
Would be awesome if you could set the default page view with this concept. I think it's currently 20 devices/facts/etc.

**Comment by sheagcraig** [comment]
Yeah, keep this open. I'll throw in the sal setting initial data setting and whatnot.

**Comment by sheagcraig** [comment]
So the datatable length settings are a little squirrely. The inventory datatables' page length are set at import time, so the app has to restart to detect any changes you make to the setting. And then datatables itself tracks what a user sets, so I'm not sure which "wins" in a test of wills.

All of the handcoded datatables in server and search use it immediately after being set, however.

**Comment by sheagcraig** [comment]
Final score:
- Creates a `server.utils.get|set_setting()` function to use instead of querying the database directly. These utilities use a json file that specifies defaults to reconfigure deleted settings (and initially configure them).
- Applies these settings throughout, and updates all instances of querying SalSettings.
- Adds a `page_length` SalSetting that controls (hopefully) the default length of DataTables throughout Sal (at least until Datatables gets some user input to the contrary).
- Overhauls and fixes the new sal version notification code so that it actually works, including implementing missing routes.
- Adds a button to the machine detail FileVault "CryptStatus" plugin that goes to Crypt if  crypt_url SalSetting is set. If a machine passes the escrow check, the link will go to the machine's info page; otherwise, it just goes to the main Crypt index.

Outstanding issues:
- `CRYPT_URL` and `ROOT_CA` are used by the cryptstatus plugin, and are set in `system_settings.py` and the Docker settings import module. Should these somehow get merged with the SalSetting of matching name (crypt_url, and add root_ca), or should we try to do it during settings import?

Option one is to remove the settings entirely from system_settings and Docker/settings_import, and just make them into regular `SalSettings`.

Option two is to try to use the SalSettings utility to set them at application startup. This unfortunately means the app (probably) has to be restarted for settings changes to take effect.

Option three is to try to somehow merge them? But I'm at the end of the week and will need to think on this one a little while.

**Comment by sheagcraig** [comment]
I guess I need to extend the `page_length` setting to API results? (#140)? @erikng and @grahamgilbert

**Comment by grahamgilbert** [comment]
Sure if you want to. I guess I’m old school in that I prefer using config files, so I really don’t mind what you do here.

**Comment by grahamgilbert** [comment]
This looks great. I'm going to merge as is. Just need some updates to the wiki, but I don't think that needs to block the release.

**Pull request merged**
