### PR TITLE
Redesign of machine_detail.html

### PR DESCRIPTION
**Pull request by chasetb**
Here's the code for the redesigned machine_detail.html page shown yesterday in the Slack channel.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
The css is generated with the less files - can you update those as well please? I don't actually edit the css directly.

**Comment by chasetb** [comment]
I did not know that. Those are just the files in ``site_static/css/less`` right? I'll add the sb-admin2 changes to the ``sb-admin-2.less`` file. Should I add the bootstrap changes to the same file? in ``variables.less``? new file altogether?

**Comment by grahamgilbert** [comment]
They can go in sb-admin-2.less - I've been trying to avoid changing the bootstrap css so it will be easier to upgrade when the time comes. One day I'll split out the custom CSS into it's own file, but there's enough extra in sb-admin-2 already that there might as well be a little more.

**Comment by chasetb** [comment]
OK, finally done!

**Pull request merged**
